version: "3"
services:
    ui:
        image: jakobleben/arrp-web-ui:release
        networks:
            - default
            - traefik-net
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
            labels:
                traefik.frontend.rule: "Host:arrp-lang.info"
                traefik.port: 80
                traefik.docker.network: traefik-net
    compiler:
        image: jakobleben/arrp-web-compiler:release
        networks:
            - default
            - traefik-net
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure

networks:
    traefik-net:
        external: true
