version: "3"
services:
    ui:
        image: jakobleben/arrp-web-ui:e988730
        ports:
            - "80:80"
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
    engine:
        image: jakobleben/arrp-web-engine:0f67eb8
        ports:
            - "8002:8000"
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
