version: "3"
services:
    pug:
        image: pug
        volumes:
            - /home/jakob/code/arrp-website/ui/pug:/input
            - html:/output
        command:
            "pug /input/pages --out /output -O \"{base_url: ''}\" --watch"

    ui:
        image: jakobleben/arrp-web-ui:1
        networks:
            - default
            - traefik-net
        volumes:
            - /home/jakob/code/arrp-website/ui:/opt/www
            - html:/opt/www/html
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
            labels:
                traefik.frontend.rule: "Host:127.0.0.1"
                traefik.port: 80
                traefik.docker.network: traefik-net
    compiler:
        image: jakobleben/arrp-web-compiler:1
        networks:
            - default
            - traefik-net
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure

networks:
    traefik-net:
        external: true

volumes:
    html:
